# Generated by Django 3.2.4 on 2021-06-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exames_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='resultado',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
